// Array with the props for each input element
export const inputs = [
    {
        id:1,
        name:"firstName",
        type:"text",
        placeholder: "Escriba su nombre/nombres",
        label:"Nombres",
    }, 
    {   id:2,
        name:"lastName",
        type:"text",
        placeholder: "Escriba su apellido/apellidos",
        label:"Apellidos",
    },
    {   id:3,
        name:"birthday",
        type:"date",
        placeholder: "Birthday",
        label:"Birthday",
    },
    {   id:4,
        name:"email",
        type:"email",
        placeholder: "Escriba su correo electrónico",
        label:"Email",
    },
    {   id:5,
        name:"password",
        type:"password",
        placeholder: "Password",
        label:"Password",
    },
    {   id:6,
        name:"confirmPassword",
        type:"password",
        placeholder: "Confirm password",
        label:"Confirm password",
    },
];