// Array with the props for each input element
export const inputs = [
    {
        id:1,
        name:"firstName",
        type:"text",
        placeholder: "Escriba su nombre/nombres",
        label:"Nombres",
        errorMessage: "No debe contener caracteres especiales y números!",
    }, 
    {   id:2,
        name:"lastName",
        type:"text",
        placeholder: "Escriba su apellido/apellidos",
        label:"Apellidos",
        errorMessage: "No debe contener caracteres especiales y números!",
    },
    {   id:3,
        name:"birthday",
        type:"date",
        placeholder: "Seleccione su cumpleaños",
        label:"Fecha de nacimiento",
        errorMessage: "",
    },
    {   id:4,
        name:"email",
        type:"email",
        placeholder: "Escriba su correo electrónico",
        label:"Email",
        errorMessage: "Debe ser un correo electrónico válido!",
    },
    {   id:5,
        name:"password",
        type:"password",
        placeholder: "Escriba su nueva contraseña",
        label:"Contraseña",
        errorMessage: "La contraseña debe tener entre 8-200 caracteres!",
    },
    {   id:6,
        name:"confirmPassword",
        type:"password",
        placeholder: "Confirme su constraseña",
        label:"Confirmar contraseña",
        errorMessage: "Las contraseñas no coinciden!",
    },
];